import {notFound} from "next/navigation";import Link from "next/link";
const data:{[k:string]:{name:string;title:string;intro:string;zones:string[]}}={
"seoul/gangnam":{name:"서울 강남구",title:"강남구 입주청소, 평수보다 현장조건부터 확인하세요",intro:"공동주택과 오피스텔이 함께 있는 생활권에서는 창호 수, 수납공간, 주차와 작업자 출입 절차가 견적 조건에 영향을 줄 수 있습니다.",zones:["대단지 공동주택","고층 오피스텔","업무·상업 생활권"]},
"seoul/songpa":{name:"서울 송파구",title:"송파구 입주청소 준비, 대단지 출입 조건까지 확인하세요",intro:"대규모 공동주택에서는 관리사무소 예약, 엘리베이터 사용과 차량 진입 절차를 청소일 전에 확인하는 것이 중요합니다.",zones:["대단지 아파트","신축·재건축 주거","생활권 중심 오피스텔"]},
"busan/haeundae":{name:"부산 해운대구",title:"해운대구 입주청소, 창호와 주거 형태를 함께 비교하세요",intro:"고층 공동주택과 상업·관광 생활권이 공존하므로 외창 가능 범위, 주차와 작업 동선을 견적 단계에서 구분해야 합니다.",zones:["고층 공동주택","해안 생활권","상업지역 주거"]},
"daegu/suseong":{name:"대구 수성구",title:"수성구 입주청소, 신축·구축 조건을 나눠 확인하세요",intro:"아파트 중심 생활권에서도 준공 시기와 수납 구조에 따라 공사 분진 또는 생활 오염의 작업 범위가 달라질 수 있습니다.",zones:["아파트 생활권","신축 공동주택","구축 주거지"]},
"gyeonggi/suwon":{name:"경기 수원시",title:"수원 입주청소 업체 찾기, 생활권별 조건부터 확인하세요",intro:"신도시형 공동주택과 구도심 주거지가 함께 있어 주차, 엘리베이터, 창호와 오염 상태를 현장별로 확인해야 합니다.",zones:["신도시 공동주택","구도심 주거","오피스텔 생활권"]}}
export function generateStaticParams(){return Object.keys(data).map(k=>{const [sido,sigungu]=k.split("/");return{sido,sigungu}})}
export default async function Page({params}:{params:Promise<{sido:string;sigungu:string}>}){const p=await params;const item=data[`${p.sido}/${p.sigungu}`];if(!item)notFound();return <><section className="pageHero"><div className="shell"><span className="eyebrow">{item.name} LOCAL GUIDE</span><h1>{item.title}</h1><p>{item.intro}</p></div></section><section className="section shell"><div className="contentGrid">{item.zones.map((z,i)=><article className="contentCard" key={z}><span className="eyebrow">LIVING AREA {i+1}</span><h2>{z}</h2><p>건물의 준공 시기, 창호와 수납공간, 작업자 출입·주차 조건을 업체에 미리 전달하세요.</p></article>)}</div><div className="areaBox" style={{marginTop:40}}><div><h2>{item.name} 견적 준비 체크</h2><p>관리사무소 출입, 엘리베이터, 주차, 수도·전기와 폐기물 여부를 청소 전에 확인하세요.</p></div><Link className="button" href="/estimate">무료 비교견적 →</Link></div></section></>}
